name: Contextos
on:
  push:
    branches: [ main ]

jobs:
  contextos:
    runs-on: ubuntu-latest
    steps:
      - name: Contextos
        run: |
          echo "Contexto de la rama: ${{ github.ref }}"
          echo "Contexto del repositorio: ${{ github.repository }}"
          echo "Contexto del actor: ${{ github.actor }}"
          echo "Contexto del evento: ${{ toJson(github.event) }}"

