name: Hola Mundo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Ejecutar el script de Hola Mundo
      run: python hola_mundo.py